import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, writeFile, mkdir, symlink, rm, readFile } from 'node:fs/promises';
import { tmpdir, hostname, platform } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { contextStatus } from './context-status.mjs';
const hash=v=>createHash('sha256').update(v).digest('hex');
test('missing/unsupported/symlink homes stay unknown and do not execute owner data',async t=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'aios-status-')));t.after(()=>rm(root,{recursive:true,force:true}));
 assert.equal((await contextStatus(join(root,'absent'))).owner,'missing');
 await writeFile(join(root,'AIOS_FORMAT'),'99\n');assert.equal((await contextStatus(root)).owner,'unsupported');
 await symlink(root,join(root,'link'));assert.equal((await contextStatus(join(root,'link'))).owner,'unavailable');
});
test('local state, personal methods and dated proof invalidate on changes without exposing contents',async t=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'aios-status-')));t.after(()=>rm(root,{recursive:true,force:true}));
 const files={'AIOS.md':'# Synthetic owner\nPrivate owner meaning','MEMORY.md':'# Memory\n- Synthetic unique preference','CONNECTIONS.md':'# Connections\nNo secrets'};
 await writeFile(join(root,'AIOS_FORMAT'),'2\n');for(const [name,value] of Object.entries(files))await writeFile(join(root,name),value);
 await mkdir(join(root,'context'));await writeFile(join(root,'context/topic.md'),'# A routed topic');
 await mkdir(join(root,'skills/personal-method'),{recursive:true});await writeFile(join(root,'skills/personal-method/SKILL.md'),'---\nname: personal-method\n---\n');
 const evidence={verified:true,verifiedAt:new Date().toISOString(),evidence:'Synthetic checked useful-work scope',sourceHashes:Object.fromEntries(Object.entries(files).map(([n,v])=>[n,hash(v)]))};
 const record={version:1,hostKey:hash(platform()+'\0'+hostname()),context:evidence,access:evidence,work:evidence};
 await writeFile(join(root,'context/codex-setup.json'),JSON.stringify(record));
 let result=await contextStatus(root);assert.equal(result.owner,'ready');assert.equal(result.routes,1);assert.equal(result.personalSkills,1);assert.equal(result.git.state,'not_configured');assert.deepEqual(result.setup,{context:'recorded',access:'recorded',work:'recorded'});
 assert.ok(!JSON.stringify(result).includes('Private owner meaning'));assert.ok(!JSON.stringify(result).includes(root));
 await writeFile(join(root,'MEMORY.md'),'# Changed memory');assert.equal((await contextStatus(root)).setup.context,'stale');
 record.hostKey='another-host';await writeFile(join(root,'context/codex-setup.json'),JSON.stringify(record));assert.equal((await contextStatus(root)).setup.access,'stale');
 await writeFile(join(root,'context/codex-setup.json'),'{bad');assert.equal((await contextStatus(root)).setup.work,'unknown');
});
test('cached remote equality is distinct from dirty local state; status performs no fetch or write',async t=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'aios-git-')));t.after(()=>rm(root,{recursive:true,force:true}));
 const cmd=(...a)=>execFileSync('git',['-C',root,...a],{encoding:'utf8'}).trim();
 await writeFile(join(root,'AIOS_FORMAT'),'2\n');await writeFile(join(root,'AIOS.md'),'# Synthetic owner');cmd('init','-q','-b','main');cmd('add','AIOS.md','AIOS_FORMAT');cmd('-c','user.name=Fixture','-c','user.email=fixture@example.test','commit','-qm','fixture');
 cmd('update-ref','refs/remotes/origin/main','HEAD');cmd('config','remote.origin.url','https://example.invalid/never-contact');cmd('config','remote.origin.fetch','+refs/heads/*:refs/remotes/origin/*');cmd('config','branch.main.remote','origin');cmd('config','branch.main.merge','refs/heads/main');
 const before=await readFile(join(root,'.git/index'));assert.equal((await contextStatus(root)).git.state,'matches_cached_remote');assert.deepEqual(await readFile(join(root,'.git/index')),before);
 await writeFile(join(root,'MEMORY.md'),'# New local preference');assert.equal((await contextStatus(root)).git.state,'local_changes');
});
test('native targets are opt-in, bounded to existing owner files and exclude symlinks',async t=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'aios-targets-')));t.after(()=>rm(root,{recursive:true,force:true}));
 await writeFile(join(root,'AIOS_FORMAT'),'2\n');await writeFile(join(root,'AIOS.md'),'# Synthetic index');await mkdir(join(root,'context'));await writeFile(join(root,'context/README.md'),'# Synthetic routes');
 await symlink(join(root,'AIOS.md'),join(root,'MEMORY.md'));
 const summary=await contextStatus(root);assert.equal(summary.fileTargets,undefined);assert.ok(!JSON.stringify(summary).includes(root));
 const native=await contextStatus(root,{includeTargets:true,includeInventory:true});assert.deepEqual(native.fileTargets,{index:join(root,'AIOS.md'),'context/README.md':join(root,'context/README.md')});
 await writeFile(join(root,'AIOS_FORMAT'),'99\n');assert.equal((await contextStatus(root,{includeTargets:true})).fileTargets,undefined);
});
test('context inventory follows actual local names, refreshes and bounds traversal without reading topic contents',async t=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'aios-inventory-')));t.after(()=>rm(root,{recursive:true,force:true}));
 await writeFile(join(root,'AIOS_FORMAT'),'2\n');await writeFile(join(root,'AIOS.md'),'# Synthetic index');
 await mkdir(join(root,'context/company'),{recursive:true});
 await writeFile(join(root,'context/company/a & b.md'),'Private topic contents must not appear');
 await writeFile(join(root,'context/ignored.json'),'{}');
 await symlink(join(root,'context/company'),join(root,'context/linked'));
 let result=await contextStatus(root,{includeInventory:true});
 assert.deepEqual(result.inventory.context.files,['context/company/a & b.md']);
 assert.equal(result.inventory.skills.available,false);assert.equal(result.fileTargets,undefined);
 assert.ok(!JSON.stringify(result).includes('Private topic contents'));
 await rm(join(root,'context/company/a & b.md'));await writeFile(join(root,'context/new-space.md'),'# Space');
 result=await contextStatus(root,{includeTargets:true,includeInventory:true});
 assert.deepEqual(result.inventory.context.files,['context/new-space.md']);
 assert.equal(result.fileTargets['context/new-space.md'],join(root,'context/new-space.md'));
 for(let i=0;i<90;i++)await writeFile(join(root,'context',i+'.md'),'# Bounded');
 result=await contextStatus(root,{includeInventory:true});assert.equal(result.inventory.context.files.length,80);assert.equal(result.inventory.context.truncated,true);
 assert.equal((await contextStatus(root)).inventory,undefined);
});
test('existing local context is available without receipts and missing core files stay incomplete',async t=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'aios-existing-')));t.after(()=>rm(root,{recursive:true,force:true}));
 await writeFile(join(root,'AIOS_FORMAT'),'2\n');
 for(const name of ['AIOS.md','MEMORY.md','CONNECTIONS.md'])await writeFile(join(root,name),'# Synthetic '+name);
 let status=await contextStatus(root);assert.equal(status.localReady,true);assert.equal(status.format,true);
 await writeFile(join(root,'AIOS_FORMAT'),'1\n');assert.equal((await contextStatus(root)).localReady,true);
 assert.deepEqual(status.setup,{context:'unknown',access:'unknown',work:'unknown'});
 await mkdir(join(root,'context'));await writeFile(join(root,'context/codex-setup.json'),'{broken');
 assert.equal((await contextStatus(root)).localReady,true);
 await rm(join(root,'CONNECTIONS.md'));assert.equal((await contextStatus(root)).localReady,false);
 await writeFile(join(root,'CONNECTIONS.md'),'<!-- empty -->');assert.equal((await contextStatus(root)).localReady,false);
 await writeFile(join(root,'AIOS_FORMAT'),'99\n');status=await contextStatus(root);assert.equal(status.localReady,false);assert.equal(status.format,false);
});
test('managed custom home precedes default; missing/ambiguous routes do not create or choose a second home',async t=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'aios-discovery-')));t.after(()=>rm(root,{recursive:true,force:true}));
 const userHome=join(root,'user'),agentHome=join(root,'agent'),custom=join(root,'custom home');
 await mkdir(userHome);await mkdir(agentHome);await mkdir(custom);
 for(const name of ['AIOS.md','MEMORY.md','CONNECTIONS.md'])await writeFile(join(custom,name),'# Synthetic '+name);
 await writeFile(join(custom,'AIOS_FORMAT'),'2\n');
 const options={userHome,agentHome,includeTargets:true};
 let status=await contextStatus(undefined,options);assert.equal(status.owner,'missing');assert.equal(status.discovery,'default');
 const bridge=`Unrelated settings\n<!-- AIOS:BEGIN -->\nAIOS entrypoint: ${custom}\n<!-- AIOS:END -->\n`;
 await writeFile(join(agentHome,'AGENTS.md'),bridge);
 status=await contextStatus(undefined,options);assert.equal(status.localReady,true);assert.equal(status.discovery,'bridge');assert.equal(status.fileTargets.index,join(custom,'AIOS.md'));
 const explicit=await contextStatus(join(root,'absent'),options);assert.equal(explicit.owner,'missing');assert.equal(explicit.discovery,'explicit');assert.equal(explicit.localReady,false);
 await writeFile(join(agentHome,'AGENTS.md'),bridge+bridge);status=await contextStatus(undefined,options);assert.equal(status.owner,'unavailable');assert.equal(status.localReady,false);
 await writeFile(join(agentHome,'AGENTS.md'),bridge.replace(custom,join(root,'moved')));status=await contextStatus(undefined,options);assert.equal(status.owner,'missing');assert.equal(status.discovery,'bridge');
 assert.deepEqual(await import('node:fs/promises').then(fs=>fs.readdir(userHome)),[]);
});
